services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    ports:
      - "10000:10000" # Blob service
      - "10001:10001" # Queue service
      - "10002:10002" # Table service

    environment:
      - AZURITE_ACCOUNTS=localuser:bG9jYWxwYXNzd29yZA== # localuser:localpassword (base64 encoded)
    volumes:
      - type: volume
        source: azurite_data
        target: /data
    command: >
      azurite -l /workspace -d /workspace/debug.log
      --blobPort 10000 --blobHost 0.0.0.0
      --queuePort 10001 --queueHost 0.0.0.0
      --tablePort 10002 --tableHost 0.0.0.0
      --loose --skipApiVersionCheck --disableProductStyleUrl

volumes:
  azurite_data: